### ISSUE TITLE
Some issues running these steps

### ISSUE THREAD

**Issue by aidanmcdermott** [ibm-cloud-docs/blockchain-sw#1]
1. In `ibp-console.yaml` the imagePullSecret property has docker-key-secret in double quotes. This did not work for me until I removed the double quotes

2. The URL to login to : `https://<NAMESPACE>-ibpconsole-console.<DOMAIN>:443` did not work for me using port 443. Instead I needed to specify the `consolePort` I specified in ibp-console.yaml. I'm using a Public VLAN. The DOMAIN I used was the cluster ingress subdomain

**Comment by pamandrejko** [comment]
https://cloud.ibm.com/docs/blockchain-sw?topic=blockchain-sw-deploy-k8

**Comment by pamandrejko** [comment]
Development has asked us not to remove the double quotes around the `docker-key-secret`.

We've update the login url:
https://cloud.ibm.com/docs/blockchain-sw?topic=blockchain-sw-deploy-k8#deploy-k8-log-in

If you are deploying the platform on IBM Cloud Private, you can access the console by browsing to the following URL:

https://<DOMAIN>:<CONSOLE_PORT>

    Replace <DOMAIN> with the value of the domain: field in the ibp-console.yaml file.
    Replace <CONSOLE_PORT> with the port that you specified in the consolePort: in the ibp-console.yaml file.
