### ISSUE TITLE
Image missing in Blockchain component overview Page

### ISSUE THREAD

**Issue by robmurgai** [ibm-cloud-docs/blockchain-sw#4]
On the [ Blockchain Overview Page](https://cloud.ibm.com/docs/blockchain-sw?topic=blockchain-sw-blockchain-component-overview), there is an image missing at the bottom of the page, where it says Example Network: Figure 1.

[Blockchain Component Overview - Missing Image.pdf](https://github.com/ibm-cloud-docs/blockchain-sw/files/5168281/Blockchain.Component.Overview.-.Missing.Image.pdf)

-- Rob Murgai (murgai@us.ibm.com)

**Comment by pamandrejko** [comment]
Fixed here https://cloud.ibm.com/docs/blockchain-sw?topic=blockchain-sw-blockchain-component-overview#blockchain-component-overview-example-network
