### ISSUE TITLE
local NPM registry

### ISSUE THREAD

**Issue by askariam** [ibm-cloud-docs/blockchain-sw#5]
In the documentation it is stated:
"your JavaScript or TypeScript chaincode will not be able to download external dependencies when the chaincode is instantiated. You need point to a local NPM registry for your chaincode to access the required dependencies. This problem does not occur if you are using Go chaincode"

The documentation does not explain how to point to a local NPM registry. Could you please direct me to the place where you document how to set this local NPM registry point?

Thank you.

**Comment by pamandrejko** [comment]
https://cloud.ibm.com/docs/blockchain-sw?topic=blockchain-sw-deploy-ocp-firewall#need-to-know

**Comment by pamandrejko** [comment]
I've updated the docs with a link to these new instructions: https://cloud.ibm.com/docs/blockchain-sw-25?topic=blockchain-sw-25-deploy-ocp-firewall#need-to-know

**Comment by pamandrejko** [comment]
Content updated in all three versions: 212, 213, 25
